{% set name = "gsutil" %}
{% set version = "5.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb18b8d2067d9a9e45c99b7614e241c173632eb66b7d3cb007979d6aee7146cf

build:
  number: 0
  noarch: python
  entry_points:
    - gsutil = gslib.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - google-auth >=2.5.0
    - python >=3.6
    - argcomplete >=1.9.4
    - crcmod >=1.7
    - fasteners >=0.14.1
    - gcs-oauth2-boto-plugin >=3.0
    - google-apitools >=0.5.32
    - google-reauth >=0.1.0
    - httplib2 ==0.20.4
    - monotonic >=1.4
    - pyopenssl >=0.13
    - retry_decorator >=1.0.0
    - six >=1.12.0
  run_constrained:
    - google-cloud-sdk <0a

test:
  imports:
    - gslib
    - gslib.addlhelp
  commands:
    - pip check
    - gsutil version
  requires:
    - pip

about:
  home: https://pypi.org/project/gsutil/
  summary: A command line tool for interacting with cloud storage services.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
