{% set name = "gsutil" %}
{% set version = "5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27a3fbf503eb7fb81dc8fa11070f13f4611682a7b24daefd46915b1eb91b1cb6

build:
  number: 0
  noarch: python
  entry_points:
    - gsutil = gslib.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - argcomplete >=1.9.4
    - crcmod >=1.7
    - fasteners >=0.14.1
    - gcs-oauth2-boto-plugin >=2.7
    - google-apitools >=0.5.32
    - google-reauth >=0.1.0
    - httplib2 >=0.18
    - mock ==2.0.0
    - monotonic >=1.4
    - pyopenssl >=0.13
    - retry_decorator >=1.0.0
    - six >=1.12.0
  run_constrained:
    - google-cloud-sdk <0a

test:
  imports:
    - gslib
    - gslib.addlhelp
  commands:
    - pip check
    - gsutil version
  requires:
    - pip

about:
  home: https://pypi.org/project/gsutil/
  summary: A command line tool for interacting with cloud storage services.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
