{% set name = "gsutil" %}
{% set version = "5.33" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26f5441e619d6244016da0ab3a11285dcd88cf32aeb571b3e28606a165c07856

build:
  number: 0
  noarch: python
  entry_points:
    - gsutil = gslib.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - google-auth-httplib2 >=0.2.0
    - google-auth ==2.17.0
    - python >={{ python_min }},<3.13
    - argcomplete >=3.5.1
    - crcmod >=1.7
    - fasteners >=0.14.1
    - gcs-oauth2-boto-plugin >=3.2
    - google-apitools >=0.5.32
    - google-reauth >=0.1.0
    - httplib2 ==0.20.4
    - monotonic >=1.4
    - pyopenssl >=0.13,<=24.2.1
    - retry_decorator >=1.0.0
    - six >=1.16.0
  run_constrained:
    - google-cloud-sdk <0a

test:
  imports:
    - gslib
    - gslib.addlhelp
  commands:
    - pip check
    - gsutil version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gsutil/
  summary: A command line tool for interacting with cloud storage services.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
